name: OrzMC
version: '1.0'
main: com.jokerhub.paper.plugin.orzmc.OrzMC
api-version: '1.20'
load: STARTUP
authors: [ wangzhizhou ]
description: OrzMC for Paper Server Plugin
website: minecraft.jokerhub.cn
commands:
  tpbow:
    description: 传送弓，射出的箭落地时会把自己传送到箭落地的位置
  guide:
    description: 获取新手教程，更快的熟悉服务器
  menu:
    description: 菜单展示