name: OrzMC
version: ${project.version}
main: com.jokerhub.paper.plugin.orzmc.OrzMC
api-version: 1.16
authors: [ wangzhizhou ]
description: OrzMC for Paper Server Plugin
website: minecraft.jokerhub.cn
