name: OrzMC
version: ${project.version}
main: com.jokerhub.paper.plugin.orzmc.OrzMC
api-version: 1.16
authors: [ wangzhizhou ]
description: OrzMC for Paper Server Plugin
website: minecraft.jokerhub.cn
commands:
  tpbow:
    description: 传送弓，射出的箭落地时会把自己传送到箭落地的位置
    usage: /<command> 使用这个传送弓射箭，可以把你传送到箭落地的位置