name: Build Check
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gradle
        uses: gradle/actions/wrapper-validation@v4
      - name: jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: build shadowJar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: ./gradlew clean build --stacktrace