name: Publish to Hangar
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
jobs:
  publish:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gradle
        uses: gradle/actions/wrapper-validation@v4
      - name: jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: publish to Hangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: ./gradlew clean publishPluginPublicationToHangar --stacktrace