name: Publish to Hangar
on:
  push:
    branches:
      - main
jobs:
  publish:
    if: github.repository_owner == 'OrzGeeker'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gradle
        uses: gradle/actions/wrapper-validation@v4
      - name: jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      # - name: build
      #   run: gradle build
      # - name: upload artifact
      #   uses: actions/upload-artifact@v3.1.2
      #   with:
      #     name: OrzMC
      #     path: target/OrzMC-1.0.jar
      - name: Publish
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: ./gradlew build publishPluginPublicationToHangar --stacktrace
